title: Fatima Mostefai
email: fmostefai090@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Master in Cellular and Molecular Medicine, RNA Methabolism
  Student in Bioinformatics
# social links
github_username: github.con/fmostefai

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
