title: Fatima Mostefai
author: Fatima Mostefai
email: fmostefai090@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Master in Cellular and Molecular Medicine, RNA Methabolism
  \n
  Student in Bioinformatics
# social links
github_username: github.com/fmostefai

show_excerpts: false # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
